<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Dual.fs" />
    <Compile Include="NewBasisCell.fs" />
    <Compile Include="NewSolution.fs" />
    <Compile Include="SampleData1.fs" />
    <Compile Include="SampleData2.fs" />
    <Compile Include="SteppingStone.fs" />
    <Compile Include="InitialFeasibleSolution.fs" />
    <Compile Include="Solver.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
